### ISSUE TITLE
Import other palette formats to swatches

### ISSUE THREAD

**Issue by oconnor0** [mitchcurtis/slate#104]
**Is your feature request related to a problem? Please describe.**
I would love to be able to load palettes in any of the formats specified on **https://lospec.com/palette-list/endesga-32**

**Describe the solution you'd like**
Being able to import any of those palettes would be nice to ease playing around with them and with interacting with other tool's palette export/import formats.

**Comment by mitchcurtis** [comment]
Thanks for the feedback!

Support for importing Paint.NET palettes will be in the next version of Slate. :)

**Comment by oconnor0** [comment]
Awesome, thanks!
