### ISSUE TITLE
Strange naming of macOS release disk image

### ISSUE THREAD

**Issue by glingy** [mitchcurtis/slate#106]
**Describe the bug**
When the macOS installer (dmg) is mounted, the name is `/Users/mitch/dev/slate-qt5_slate_fw-Release/qtc_qt5_slate_fw_Release/install-root/Slate`.

**To Reproduce**
Mount the macOS disk image under releases

**Expected behavior**
I would expect the name to be Slate, not the path to the release of slate in Mitch's computer.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Irrelevant
 - Version: 0.5.0

**Screenshots**

<img width="770" alt="screen shot 2018-12-30 at 5 53 22 pm" src="https://user-images.githubusercontent.com/17791817/50553453-ce0c9880-0c5b-11e9-8c2d-7d6d0b06defb.png">

**Comment by mitchcurtis** [comment]
Yeah, unfortunately I have no idea how to remove it. I already asked about it a while ago:

https://stackoverflow.com/questions/44853161/what-is-the-purpose-of-the-path-at-the-top-of-the-window-of-a-mounted-dmg-file

**Comment by mitchcurtis** [comment]
It can be fixed by simply deploying it differently, so I just need to remember to do it the correct way for the next release. :)
