### ISSUE TITLE
Make brush/pick/erase easier

### ISSUE THREAD

**Issue by devnewton** [mitchcurtis/slate#109]
When drawing sprite or tile with transparent pixels, I switch a lot between brush, pick and eraser tools.

It would be more productive to limit tool switch by either:

- having left click for brush, right click for erase, ctrl+left click for pick.
- having left click for brush, right click for pick, making transparent pixel pickable.

**Comment by mitchcurtis** [comment]
Yeah I have to admit I've basically never used right click for switching foreground/background colours... I think having some kind of combo box with a list of options for right click would be good. Oh, and it should default to right click being erase.

Ctrl+left click to pick is an interesting idea, and one that would solve #90.

**Comment by mitchcurtis** [comment]
There is a bit of conflict here... if I make this apply for all tools, it breaks the fix for #75. So this will only apply when the pen tool is selected, which makes more sense to me anyway.

**Comment by mitchcurtis** [comment]
There will be a setting to control this in the next release:

<img width="527" alt="screen shot 2019-03-03 at 5 58 23 pm" src="https://user-images.githubusercontent.com/6002340/53698519-0b1d1480-3dde-11e9-84d3-bf9e5873b407.png">

There are three settings:

<img width="520" alt="screen shot 2019-03-03 at 5 58 30 pm" src="https://user-images.githubusercontent.com/6002340/53698520-0bb5ab00-3dde-11e9-98e4-2cf1f5afbdd3.png">

Thanks for your feedback!

**Comment by devnewton** [comment]
Great work !
