### ISSUE TITLE
No test case to cover MenuBar

### ISSUE THREAD

**Issue by arunpkqt** [mitchcurtis/slate#111]
I could not find any test case which covers using the options from the MenuBar. I was trying to find the MenuBar from C++ and I am not able to click on any of the Menu Item.

**Comment by mitchcurtis** [comment]
I don't accept bug reports for missing tests, sorry. :) If you have a bug in the application itself, feel free to report that instead.

If you need help with Qt, I suggest taking a look at this page:

https://wiki.qt.io/Online_Communities
