### ISSUE TITLE
"libicui18n.so.60: cannot open shared object file: No such file or directory" on Linux

### ISSUE THREAD

**Issue by mitchcurtis** [mitchcurtis/slate#112]
Users have reported the following error on Mint and Solus distributions:

> error while loading shared libraries: libicui18n.so.60: cannot open shared object file: No such file or directory

I saw a similar issue with another Qt application a while back:

https://bugreports.qt.io/browse/QDS-455

**Comment by mitchcurtis** [comment]
Upon installing a newer version of libicui18n.so.60, one user gets another error:

> ./Slate: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory

**Comment by mitchcurtis** [comment]
According to the comments in https://github.com/AIIX/Mycroft-Ai-QtApplication/issues/4, one of solving this is to bundle libicui18n and libpng with the app. I'm not using linuxdeployqt though, and I'm building statically...

**Comment by mitchcurtis** [comment]
I've been told that the easiest way to fix this is indeed to ship the ICU libs with the app. This will require wrapping Slate in a shell script which sets LD_LIBRARY_PATH beforehand.

**Comment by mitchcurtis** [comment]
It seems that I can actually run a dynamically-built Slate deployed with linuxdeployqt without problems now, so I think I'll try that instead, as it will allow me to use pre-built binaries in the future:

https://github.com/mitchcurtis/slate/commit/4bede2be54a194f9bc033d56e4df3d300065415a

As a bonus side effect of this, it seems that linuxdeployqt correctly deploys the ICU libraries, so that patch should fix this.

**Comment by LJNIC** [comment]
The newest released fixed this problem for me, thank you! :+1:

**Comment by mitchcurtis** [comment]
Good to hear! Thanks for the feedback!
