### ISSUE TITLE
Minor selection annoyance

### ISSUE THREAD

**Issue by acoolstraw** [mitchcurtis/slate#144]
**Describe the bug**
When you begin a selection, the guiding dotted lines are offset by a pixel to the northwest. If you have a 3x3 canvas, you have a single pixel in the middle and you try to select it with the horizontal and vertical guiding lines bordering the pixel's bottom and right, you'd start the selection from the border of the canvas.

**To Reproduce**
1. Start selection
2. You'll see that the selection begins from a pixel to the northeast

**Expected behavior**
I expect the guiding lines to select things inside of them

**Screenshots**
![image](https://user-images.githubusercontent.com/45886986/72170181-6aed3000-339e-11ea-93ec-4eb4147b7be5.png)
![image](https://user-images.githubusercontent.com/45886986/72170190-70e31100-339e-11ea-99f4-57a5bba5927c.png)

**Environment (please complete the following information):**
 - OS: Kubuntu 19.04
 - Slate Version Slate: 0.8.0 (with Wine)

**Additional context**

**Comment by mitchcurtis** [comment]
Hi, thanks for the feedback!

Do I understand you correctly that the expected selection would have been this (in red):

![expected](https://user-images.githubusercontent.com/6002340/72196748-515aef80-3455-11ea-86bc-2d1545153e8b.png)

**Comment by acoolstraw** [comment]
Yes

**Comment by mitchcurtis** [comment]
Thanks! :)
