### ISSUE TITLE
Still in Development?

### ISSUE THREAD

**Issue by Venus007e** [mitchcurtis/slate#163]
Its not really an issue, but just a quick question. Is slate still being developed? I really like it and am probably going to use it as my main pixelart editor, but as i said i´m just wondering if there are more updates coming. I just dont like it at all to use discontinued software

**Comment by mitchcurtis** [comment]
It sure is! I am using it for my game and sometimes also just basic image editing. I don't have any plans to stop working on it, but the work I do on it is mostly just... whenever I feel like it. So it's not a regular schedule but won't be stopping. :)

**Comment by mitchcurtis** [comment]
Oh, by the way, great to hear that you like it! :D

**Comment by mitchcurtis** [comment]
`git rev-list v0.9.0..HEAD --count` tells me that there are 100 commits since the last release. You can also check e.g. https://github.com/mitchcurtis/slate/commits/master to see when recent commits were made, or something like https://github.com/mitchcurtis/slate/pulse/monthly for an overview.
