### ISSUE TITLE
Add an option to put panels on the left side of the screen

### ISSUE THREAD

**Issue by mitchcurtis** [mitchcurtis/slate#164]

**Comment by Venus007e** [comment]
yes please :D

**Comment by mitchcurtis** [comment]
Done in 9f8214724aec9afb1c65b4c31fd4978853c270c6.

**Comment by mitchcurtis** [comment]
Though there is still the old selection panning bug: #165

**Comment by mitchcurtis** [comment]
Had to remove this feature for now as it caused a bug that needs to be fixed first: a00811779d096e431e35c081732d84a1587025a4.
