### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by Xicrosoft** [mitchcurtis/slate#184]
**Is it possible to add Chinese translation？**

**Comment by mitchcurtis** [comment]
Absolutely, if someone is willing to provide the translation.

**Comment by yeahitsjan** [comment]
Whats with #157? Seems like there were some chinese translations already.

**Comment by mitchcurtis** [comment]
> Whats with #157? Seems like there were some chinese translations already.

Oh, right! I forgot all about that! :D

If there are issues with the Chinese translation, I'm happy to try to review any patches (with the help of Google Translate!).
