### ISSUE TITLE
Binary Windows 0.10 release crashes on start

### ISSUE THREAD

**Issue by demiantres** [mitchcurtis/slate#31]

**Comment by mitchcurtis** [comment]
Hey, thanks for the feedback!

Are you able to get a stack trace (via e.g. Creator or Visual Studio)?

**Comment by demiantres** [comment]
I downloaded the Windows release package and ran the exe file. Probably one of the dlls or Qt Qml files is missing.

**Comment by mitchcurtis** [comment]
Does it work if you install this:

https://aka.ms/vs/15/release/vc_redist.x64.exe

(from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)

**Comment by mitchcurtis** [comment]
Some future reading material for me:

https://stackoverflow.com/a/40077368/904422
https://stackoverflow.com/a/35555357/904422
https://stackoverflow.com/a/32602828/904422

**Comment by mitchcurtis** [comment]
https://github.com/mitchcurtis/slate/issues/42.

**Comment by mitchcurtis** [comment]
This is now fixed by including the redist file in the Windows download. Unfortunately this also almost doubles its size.
