### ISSUE TITLE
Unable to clone the submodules

### ISSUE THREAD

**Issue by sanojsubran** [mitchcurtis/slate#35]
Hi,

As mentioned in the README doc, I tried to clone the submodules, but I was getting the following errors. Could anyone please help me on this?

> git submodule init
Submodule '3rdparty/pickawinner' (git@github.com:mitchcurtis/pickawinner.git) registered for path '3rdparty/pickawinner'
Submodule '3rdparty/qt-undo' (git@github.com:mitchcurtis/qt-undo.git) registered for path '3rdparty/qt-undo'

> git submodule update
Cloning into 'E:/all_files/projects/qt/slate_code/slate/3rdparty/pickawinner'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mitchcurtis/pickawinner.git' into submodule path 'E:/all_files/projects/qt/slate_code/slate/3rdparty/pickawinner' failed
Failed to clone '3rdparty/pickawinner'. Retry scheduled
Cloning into 'E:/all_files/projects/qt/slate_code/slate/3rdparty/qt-undo'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mitchcurtis/qt-undo.git' into submodule path 'E:/all_files/projects/qt/slate_code/slate/3rdparty/qt-undo' failed
Failed to clone '3rdparty/qt-undo'. Retry scheduled
Cloning into 'E:/all_files/projects/qt/slate_code/slate/3rdparty/pickawinner'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mitchcurtis/pickawinner.git' into submodule path 'E:/all_files/projects/qt/slate_code/slate/3rdparty/pickawinner' failed
Failed to clone '3rdparty/pickawinner' a second time, aborting

**Comment by mitchcurtis** [comment]
Have you tried you the https option when cloning?

**Comment by mitchcurtis** [comment]
I'm not sure if this is relevant in this case, but have you added your SSH key to GitHub?

**Comment by mitchcurtis** [comment]
Closing this for now until I get more info, as I don't think it's an issue in Slate.

**Comment by mitchcurtis** [comment]
@sanojsubran this should just work now, thanks to @fgaz. :)

**Comment by sanojsubran** [comment]
@fgaz @mitchcurtis Thanks. It worked. :)
