### ISSUE TITLE
Releases for Linux?

### ISSUE THREAD

**Issue by deshipu** [mitchcurtis/slate#46]
Hi, I wanted to try this editor, but I couldn't find any released binaries for Linux. I decided to try and build it myself, so I went looking for QT 5.11 — turns out it's not released yet. Then I tried to build the beta release of it, and it doesn't build on Linux due to ^M characters in all the configure scripts. At this point I simply gave up.

Any chance for Linux binaries to be included in the releases?

**Comment by mitchcurtis** [comment]
Hi, thanks for trying it out. Sorry that it didn't build for you. As Qt Quick Controls 2 is fairly new and new features and fixes are coming in all the time, I need to use the latest version to take advantage of them.

I've briefly looked into binaries for Linux (e.g. flatpak) but didn't get very far with it. I have an Ubuntu machine that I can build binaries on, so I could try that?

**Comment by deshipu** [comment]
That would work for me, thank you!
I got QT5.10 installed and tried to build an earlier release that required that version, but I can't get pickawinner compiled — it keeps complaining about missing qml-private quick-private quicktemplates2-private. Could it be that there are more dependencies that are not listed?

**Comment by mitchcurtis** [comment]
{quote}
I got QT5.10 installed and tried to build an earlier release that required that version, but I can't get pickawinner compiled — it keeps complaining about missing qml-private quick-private quicktemplates2-private. Could it be that there are more dependencies that are not listed?
{quote}

I just tried building pickawinner with a pre-built Qt 5.10.0 on Mac and it worked fine, so I'm not sure that the issue is there.

**Comment by mitchcurtis** [comment]
I got very close to a working release build, but ran into a bug which I think is an issue in Qt:

https://bugreports.qt.io/browse/QTBUG-67429

**Comment by samvdkris** [comment]
Just wanted to say this looks really awesome. I would really appreciate a Linux build as well. :)

**Comment by mitchcurtis** [comment]
> Just wanted to say this looks really awesome. I would really appreciate a Linux build as well. :)

Thanks! I'll try to look into the release build issue to see if I can get this moving again.

**Comment by mitchcurtis** [comment]
That was a wild ride. I ended up building statically. The bug seems to be here:

https://github.com/probonopd/linuxdeployqt/issues/280

Here's a Linux (Ubuntu) build - I hope it works for you! :)

https://github.com/mitchcurtis/slate/releases/tag/v0.0.12

**Comment by deshipu** [comment]
Thank you very much! It seems to be working at a first glance, I will give it some more testing. One thing I noticed so far is that when the cross or box cursor is displayed, the movement of it has a perceptible lag, which is a bit annoying when drawing. That doesn't happen when a hand cursor is displayed (inside a selection), so I suspect it's something about the custom cursor shape.

**Comment by deshipu** [comment]
There is also no menu bar being displayed — I noticed there is a menu bar in the Windows screenshots.

**Comment by mitchcurtis** [comment]
> Thank you very much! It seems to be working at a first glance, I will give it some more testing. One thing I noticed so far is that when the cross or box cursor is displayed, the movement of it has a perceptible lag, which is a bit annoying when drawing. That doesn't happen when a hand cursor is displayed (inside a selection), so I suspect it's something about the custom cursor shape.

Could you please create a bug report for this (along with a video or GIF of it in action if you don't mind)? I haven't noticed any slowness, but I can imagine that it's indeed due to it being a custom Item cursor instead of a system cursor.

> There is also no menu bar being displayed — I noticed there is a menu bar in the Windows screenshots.

Which OS are you on, and what kind of menu bar does it use? It's probably https://github.com/mitchcurtis/slate/issues/41, which links to the bug in Qt:

https://bugreports.qt.io/browse/QTBUG-67426

**Comment by deshipu** [comment]
I have reported the cursor lag under #52, but I am at a loss about how I could record this on a video — the lag is between the mouse movement and cursor movement, so I would need to somehow record both in sync? And the lag is small — felt rather than seen — so I have no idea what framerate I would need to have to make it visible on video.

As for the menu bar, I'm testing it on Xubuntu 17.10 without any special "kind" of menu bar — just the normal GTK/QT menu bars that you can usually see near the top of the windows. The Slate window misses it.

**Comment by mitchcurtis** [comment]
> I have reported the cursor lag under #52, but I am at a loss about how I could record this on a video — the lag is between the mouse movement and cursor movement, so I would need to somehow record both in sync? And the lag is small — felt rather than seen — so I have no idea what framerate I would need to have to make it visible on video.

No worries, that's fine. :)

> As for the menu bar, I'm testing it on Xubuntu 17.10 without any special "kind" of menu bar — just the normal GTK/QT menu bars that you can usually see near the top of the windows. The Slate window misses it.

Hmm, I dunno what kind of menus they are, but it sounds like you're saying they're Windows-style menus; integrated with the window itself as opposed to the Unity/macOS style "global" menu bar that sits at the top of the desktop?

**Comment by deshipu** [comment]
Yes, they are integrated with the application window.

**Comment by mitchcurtis** [comment]
Hmmm, damn. I've added it here:

https://bugreports.qt.io/browse/QTBUG-67426
