### ISSUE TITLE
Trying to use the select tool while in tileset mode causes a crash

### ISSUE THREAD

**Issue by Ednihaf** [mitchcurtis/slate#55]
When editing a tileset, attempting to select something (using the "M" key shortcut) and then moving it causes the program to crash.

**Comment by mitchcurtis** [comment]
Thanks for the report. I haven't implemented the selection tool for tileset projects yet, as my focus has been on the image and layered image projects lately. Feel free to open a new issue that suggests that the selection be implemented for tileset projects, but I can't guarantee that I'll find the time to implement it.
