### ISSUE TITLE
No Linux release for the latest version?

### ISSUE THREAD

**Issue by sbrl** [mitchcurtis/slate#71]
I'd love to check this sprite editor out, as it looks really cool! Unfortuantely, I use Linux - and whilst support is advertised in the README, upon going to the _Releases_ page I am met with only macOS binaries for the last 2 releases.

Is there an up-to-date binary for Linux x64 available please?

**Comment by mitchcurtis** [comment]
Hi, thanks for the feedback. :)

I will try to upload some Linux binaries today.

In the meantime, the latest Linux binaries are not that old; the last two releases contain mostly minor improvements since 0.1.0:

https://github.com/mitchcurtis/slate/releases/tag/v0.1.0

**Comment by mitchcurtis** [comment]
I switched to a new build system in v0.3.0, so there have been some hiccups getting deployment working. Surprisingly, Windows just works, but Mac and Linux are giving me issues. :)

**Comment by sbrl** [comment]
Huh! Thanks for the info :-)

**Comment by mitchcurtis** [comment]
https://bugreports.qt.io/browse/QTBUG-70711 is blocking this currently.

**Comment by mitchcurtis** [comment]
and https://github.com/probonopd/linuxdeployqt/issues/280 kinda blocks me from deploying a dynamically linked build.

**Comment by sbrl** [comment]
Thanks for the update! Here's hoping that those issues are resolved :slightly_smiling_face:

**Comment by mitchcurtis** [comment]
I've fixed the issues preventing Slate from being run when statically linked, but now that I can run it I see that there are graphical issues which are too nasty to release it with. :( Still more work to do...

**Comment by mitchcurtis** [comment]
Done! Please let me know if it works for you, and feel free to report bugs and feature suggestions. :)

https://github.com/mitchcurtis/slate/releases/tag/v0.4.1
