### ISSUE TITLE
Unable to save tileset as anything other than .stp

### ISSUE THREAD

**Issue by robbiepee** [mitchcurtis/slate#72]
I'm using Slate to draw tiles to be used with another program like Tiled, which doesn't support .stp - what I need is a png of the edited tileset without grid lines, but the "export" button is greyed out in tileset mode. I can't even export the tiles from tileset mode to their own project files. This probably falls under "improvement," because I don't think it's a result of a glitch.

**Comment by robbiepee** [comment]
on another note entirely, I'm unable to set the secondary color, and it'd be nice to have some parameters with the texture fill feature. Adding the ability to put a pallet of a few colors that are used exclusively would be nice - I believe you're using perlin noise and mapping brightness and saturation to the gradients - it shouldn't be too hard to restrict it to two or three user-picked colors in order of brightness. don't really know where else to put this, so it's here

**Comment by robbiepee** [comment]
Ohhhh, it saves over the existing tileset image. Okay lol, I just had the
original in a different folder than I'd been saving to, so I couldn't see
that it did that. Sorry 'bout that.
My problem with the background color is that I can select it, but I can't
use the colorpicker on it.

**Comment by mitchcurtis** [comment]
> Ohhhh, it saves over the existing tileset image. Okay lol, I just had the
original in a different folder than I'd been saving to, so I couldn't see
that it did that. Sorry 'bout that.

No worries, the documentation could be better... I've got it on my to-do list to improve it.

> My problem with the background color is that I can select it, but I can't
use the colorpicker on it.

Do you mean that the colour picker tool applies to the primary instead of the secondary? That seems like a bug: https://github.com/mitchcurtis/slate/issues/75

**Comment by robbiepee** [comment]
Yeah. My thought would be that either the colorpicker should apply to the
secondary with right click, or while the secondary is selected. Or perhaps
just a button to swap the primary and secondary colors, which could replace
selecting them manually.

**Comment by mitchcurtis** [comment]
The colour picker issue is fixed - again, thanks for the feedback!

**Comment by robbiepee** [comment]
No problemo! Your program appears to be the only one that does several of
the things it does, and it's pretty damn good at it, so suggesting ways to
make it even better is my way of supporting your work lol
