### ISSUE TITLE
No executable?

### ISSUE THREAD

**Issue by Tuckertcs** [mitchcurtis/slate#78]
There's no executable or jar file to run the thing

**Comment by mitchcurtis** [comment]
Are you on Windows? slate.exe is in the 0.3.0 zip.

**Comment by Tuckertcs** [comment]
If you mean
https://github.com/ianstormtaylor/slate/releases/tag/slate-html-serializer%400.3.0
this zip then idk what you're talking about, it's a bunch of source files
no exe to run it.

**Comment by mitchcurtis** [comment]
> https://github.com/ianstormtaylor/slate/releases/tag/slate-html-serializer%400.3.0

That's not my repo. :D

**Comment by Tuckertcs** [comment]
sorry as a user of software and not a programmer I don't understand github
or how to get a finished program from it rather than source codes.

**Comment by Tuckertcs** [comment]
where do I type the npm stuff into? a cmd? Sorry most software I download
comes finished in an exe, jar, or installer

**Comment by mitchcurtis** [comment]
The command prompt, yeah. You should ask for help on the correct GitHub repo, though. I don't have time to give assistance to other projects.
