### ISSUE TITLE
cant build; no .pro file

### ISSUE THREAD

**Issue by nonchip** [mitchcurtis/slate#85]
i guess the `.qbs` is meant to do something  but neither me nor `file` know what that's supposed to be (google says apparently http://doc.qt.io/qbs/overview.html is a thing now, never heard of it before, sounds like a qmake successor? my distro's repo also doesn't know it, i guess it's part of some qt lib?) and your readme specifically mentions `qmake slate.pro`.
so i guess the instructions might be outdated?

can you please tell me (and the readme) how to build it instead?

**Comment by mitchcurtis** [comment]
Ah, whoops, I forgot to update the readme after the recent build system changes.

**Comment by mitchcurtis** [comment]
Let me know if this works:

https://github.com/mitchcurtis/slate/blob/master/README.md

I always build with Creator since I'm new to Qbs.

**Comment by nonchip** [comment]
https://blog.qt.io/blog/2018/10/29/deprecation-of-qbs/

**Comment by mitchcurtis** [comment]
Yep, that indeed sucks. :( I've been pushing doc patches lately trying to improve it and then we get told that it's being dropped.

I'm not sure what the build system for Slate will be in the future, but as it stands it's fully possible to build it with Qbs, so I so no need to switch to cmake yet. :)

**Comment by nonchip** [comment]
when you switch, i can recommend cmake actually. well or qmake of course, for something a bit more fire&forget.

**Comment by mitchcurtis** [comment]
I started off with qmake but switched to Qbs because it was easier to use, despite having less documentation. Honestly I'm not looking forward to switching to cmake, but maybe I should just try it before complaining. :D

**Comment by nonchip** [comment]
i've never used it for qt projects (when i was still using qt, when it was still trolltech, qmake was pretty much the only thing around), but i've used cmake for a bunch of other things, from C/C++ desktop stuff to embedded to moonscript to even latex rendering and i must say once you get used to a few core concepts it's really nice to use :D

**Comment by mitchcurtis** [comment]
Good to know. :)
