### ISSUE TITLE
win32 support

### ISSUE THREAD

**Issue by c-sanchez** [mitchcurtis/slate#86]
Hi Slate looks nice, but I wonder if possible an win32 build, it's a pity that they can only be downloaded 64 bits verions :(

**Comment by c-sanchez** [comment]
Nice! thank you so much :D

**Comment by c-sanchez** [comment]
Hi @mitchcurtis, did you forget build the 32-bit for Windows?
Is not avaialbe with the recent 0.9.0 :(

**Comment by mitchcurtis** [comment]
Yes, it looks like I did, sorry. Unfortunately I spent all of last weekend trying to get different Linux distros to work and eventually ran out of patience. It takes too much of my time supporting 3 platforms as it is, so I won't be creating binaries for others, sorry.
